name: Login Performance Monitor

on: 
  schedule:
    - cron: "*/10 * * * *" # Every 10 minutes
  workflow_dispatch:


jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"
      
      - name: Install dependencies
        run: bun install

      - name: Run performance monitor
        run: bun start
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TZ: Africa/Lagos

      - name: Commit and push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add results.csv
          git commit -m "Performance data: $(TZ=Africa/Lagos date)" || exit 0
          git push origin main
